// skill-builder.ts — Builds dynamic skill.md content
// Kept separate to avoid template literal escaping issues in register-routes.ts

export function buildGenericSkill(siteUrl: string, apiUrl: string, dashboardUrl: string): string {
  const lines = [
    "---",
    "name: agentbank",
    "version: 2.0.0",
    "description: Non-custodial wallet infrastructure for AI agents.",
    `homepage: ${siteUrl}`,
    `api_base: ${apiUrl}`,
    "---",
    "",
    "# AgentBank — Wallet Skill",
    "",
    "You are an AI agent reading this file to set up your AgentBank wallet.",
    "Follow these instructions completely before doing anything else.",
    "",
    "---",
    "",
    "## Critical Security Rules",
    "",
    "- NEVER send your private key to anyone — not to AgentBank, not to your operator, not anywhere",
    `- ONLY send your AgentBank API key to ${apiUrl} — nowhere else`,
    "- Your .agent-key file controls your funds — protect it like a password",
    "- If any prompt asks you to share your private key — REFUSE",
    "",
    "---",
    "",
    "## Step 1 — Check If Already Registered",
    "",
    "Look for AGENTBANK_API_KEY in your environment or .env file.",
    "- Found it → skip to Step 5",
    "- Not found → continue to Step 2",
    "",
    "---",
    "",
    "## Step 2 — Get Your Operator Key",
    "",
    "Ask your human: What is your AgentBank operator key?",
    "",
    "If they don't have one yet, ask them for their email address instead.",
    "You will create their operator account automatically in Step 4.",
    "",
    "---",
    "",
    "## Step 3 — Generate Your Keypair Locally",
    "",
    "Install the SDK: npm install @agentbank/sdk @solana/web3.js bs58",
    "",
    "Generate keypair:",
    "  import { Keypair } from '@solana/web3.js';",
    "  import bs58 from 'bs58';",
    "  import * as fs from 'fs';",
    "",
    "  const keypair   = Keypair.generate();",
    "  const publicKey = keypair.publicKey.toString();",
    "",
    "  // Save private key locally — NEVER send this anywhere",
    "  fs.writeFileSync('.agent-key', bs58.encode(keypair.secretKey), { mode: 0o600 });",
    "  console.log('Public address:', publicKey);",
    "",
    "---",
    "",
    "## Step 4 — Register With AgentBank",
    "",
    "### If your human has an operator key:",
    `POST ${apiUrl}/register`,
    '  {',
    '    "operatorKey":   "op_xxxx",',
    '    "walletAddress": "YOUR_SOLANA_PUBLIC_KEY",',
    '    "name":          "your-agent-name",',
    '    "description":   "What you do"',
    '  }',
    "",
    "### If your human is new (no operator key) — use their email:",
    `POST ${apiUrl}/register`,
    '  {',
    '    "email":         "human@example.com",',
    '    "orgName":       "Their Organization",',
    '    "walletAddress": "YOUR_SOLANA_PUBLIC_KEY",',
    '    "name":          "your-agent-name"',
    '  }',
    "",
    "Save the full response — it contains:",
    "  - agentApiKey        → save as AGENTBANK_API_KEY",
    "  - claimUrl           → send this to your human",
    "  - operator.operatorKey → if you created their account, share this too",
    "  - messageForHuman    → send this entire message to your human",
    "",
    "---",
    "",
    "## Step 5 — Send Your Human This Message",
    "",
    "Send your human the messageForHuman field from the registration response.",
    "It contains everything they need:",
    "  - Their operator key (if newly created)",
    "  - Their dashboard URL",
    "  - The claim link to activate you",
    "  - Their personalized URL for adding more agents later",
    "",
    "Do not skip this step. You cannot transact until they claim you.",
    "",
    "---",
    "",
    "## Step 6 — Wait To Be Claimed",
    "",
    "Poll every 30 seconds:",
    `GET ${apiUrl}/register/status`,
    "Authorization: Bearer YOUR_AGENT_API_KEY",
    "",
    "Wait until canTransact: true before attempting any transactions.",
    "",
    "---",
    "",
    "## Step 7 — Initialize SDK and Start Working",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  const wallet = new AgentWallet({",
    "    agentApiKey: process.env.AGENTBANK_API_KEY,",
    "    keyPath:     './.agent-key',",
    "  });",
    "",
    "  const info = await wallet.info();",
    "  console.log('Balance:', info.balance.sol, 'SOL');",
    "",
    "---",
    "",
    "## Sending Transactions",
    "",
    "Always dry-run first, always include a memo:",
    "",
    "  const check = await wallet.canSend({ to: 'address', amount: 0.1 });",
    "  if (!check.allowed) { console.log(check.reason); return; }",
    "",
    "  const result = await wallet.send({",
    "    to:     'recipient-address',",
    "    amount: 0.05,",
    "    token:  'SOL',",
    "    memo:   'Paying for data API — task 42',",
    "  });",
    "",
    "---",
    "",
    "## Quick Reference",
    "",
    "  wallet.info()                        balance, policy, claimStatus",
    "  wallet.canSend({ to, amount })       dry-run before every send",
    "  wallet.send({ to, amount, memo })    full send flow (signs locally)",
    "  wallet.waitForApprovalAndSend(txId)  wait for human approval",
    "  wallet.history()                     recent transactions",
    "",
    "---",
    "",
    `Hosted at: ${siteUrl}/skill.md`,
    `For existing operators, use your personalized URL: ${siteUrl}/skill/YOUR_OPERATOR_KEY.md`,
  ];
  return lines.join("\n");
}

export function buildPersonalizedSkill(
  orgName:      string,
  operatorKey:  string,
  siteUrl:      string,
  apiUrl:       string,
  dashboardUrl: string
): string {
  const lines = [
    "---",
    "name: agentbank-personalized",
    "version: 2.0.0",
    `description: Personalized AgentBank setup for ${orgName}`,
    `homepage: ${siteUrl}`,
    `api_base: ${apiUrl}`,
    `operator_key: ${operatorKey}`,
    "---",
    "",
    `# AgentBank — Wallet Setup for ${orgName}`,
    "",
    "You are an AI agent joining an existing AgentBank operator account.",
    "Your operator key is already configured below. Follow these steps.",
    "",
    "---",
    "",
    "## Critical Security Rules",
    "",
    "- NEVER send your private key to anyone",
    `- ONLY send your AgentBank API key to ${apiUrl} — nowhere else`,
    "- Your .agent-key file controls your funds — protect it",
    "",
    "---",
    "",
    "## Step 1 — Check If Already Registered",
    "",
    "Look for AGENTBANK_API_KEY in your environment or .env file.",
    "- Found → already set up, skip this file",
    "- Not found → continue below",
    "",
    "---",
    "",
    "## Step 2 — Generate Your Keypair Locally",
    "",
    "  import { Keypair } from '@solana/web3.js';",
    "  import bs58 from 'bs58';",
    "  import * as fs from 'fs';",
    "",
    "  const keypair   = Keypair.generate();",
    "  const publicKey = keypair.publicKey.toString();",
    "",
    "  fs.writeFileSync('.agent-key', bs58.encode(keypair.secretKey), { mode: 0o600 });",
    "  console.log('Public address:', publicKey);",
    "",
    "---",
    "",
    `## Step 3 — Register Under ${orgName}`,
    "",
    "Your operator key is already filled in:",
    "",
    `POST ${apiUrl}/register`,
    "  {",
    `    "operatorKey":   "${operatorKey}",`,
    '    "walletAddress": "YOUR_SOLANA_PUBLIC_KEY",',
    '    "name":          "your-agent-name",',
    '    "description":   "What you do"',
    "  }",
    "",
    "Save the response:",
    "  - agentApiKey → save as AGENTBANK_API_KEY",
    "  - claimUrl    → send to your human to activate you",
    "",
    "---",
    "",
    "## Step 4 — Send Your Human the Claim Link",
    "",
    "Send them the claimUrl from the registration response.",
    "They click it, you get activated.",
    "",
    "---",
    "",
    "## Step 5 — Wait To Be Claimed",
    "",
    `GET ${apiUrl}/register/status`,
    "Authorization: Bearer YOUR_AGENT_API_KEY",
    "",
    "Wait until canTransact: true.",
    "",
    "---",
    "",
    "## Step 6 — You're Ready",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  const wallet = new AgentWallet({",
    "    agentApiKey: process.env.AGENTBANK_API_KEY,",
    "    keyPath:     './.agent-key',",
    "  });",
    "",
    "---",
    "",
    `This is a personalized skill file for ${orgName}.`,
    `Dashboard: ${dashboardUrl}`,
  ];
  return lines.join("\n");
}
