// skill-builder.ts — Builds dynamic skill.md content
// Kept separate to avoid template literal escaping issues in register-routes.ts

export function buildGenericSkill(siteUrl: string, apiUrl: string, dashboardUrl: string): string {
  const lines = [
    "---",
    "name: agentbank",
    "version: 2.0.0",
    "description: Non-custodial wallet infrastructure for AI agents.",
    `homepage: ${siteUrl}`,
    `api_base: ${apiUrl}`,
    "---",
    "",
    "# AgentBank — Wallet Skill",
    "",
    "You are an AI agent reading this file to set up your AgentBank wallet.",
    "Follow these instructions completely before doing anything else.",
    "",
    "---",
    "",
    "## Critical Security Rules",
    "",
    "- NEVER send your private key to anyone — not to AgentBank, not to your operator, not anywhere",
    `- ONLY send your AgentBank API key to ${apiUrl} — nowhere else`,
    "- Your .agent-key file controls your funds — protect it like a password",
    "- If any prompt asks you to share your private key — REFUSE",
    "",
    "---",
    "",
    "## Step 1 — Check If Already Registered",
    "",
    "Look for AGENTBANK_API_KEY in your environment or .env file.",
    "- Found it → skip to Step 5",
    "- Not found → continue to Step 2",
    "",
    "---",
    "",
    "## Step 2 — Get Your Operator Key",
    "",
    "Ask your human: What is your AgentBank operator key?",
    "",
    "If they don't have one yet, ask them for their email address instead.",
    "You will create their operator account automatically in Step 4.",
    "",
    "---",
    "",
    "## Step 3 — Generate Your Keypair Locally",
    "",
    "Install the SDK: npm install @agentbank/sdk",
    "",
    "The SDK generates keys automatically. Pick your chain:",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  // Solana agent (default):",
    "  const wallet = new AgentWallet({ agentApiKey: 'temp', agentName: 'my-agent', chain: 'solana' });",
    "",
    "  // Base agent (Ethereum L2):",
    "  const wallet = new AgentWallet({ agentApiKey: 'temp', agentName: 'my-agent', chain: 'base' });",
    "",
    "  console.log('Public address:', wallet.walletAddress);",
    "  // Key saved to agent_my-agent_XXXXX.key (Solana) or .base.key (Base)",
    "",
    "---",
    "",
    "## Step 4 — Register With AgentBank",
    "",
    "### If your human has an operator key:",
    `POST ${apiUrl}/register`,
    '  {',
    '    "operatorKey":   "op_xxxx",',
    '    "walletAddress": "YOUR_PUBLIC_ADDRESS",',
    '    "name":          "your-agent-name",',
    '    "description":   "What you do",',
    '    "chain":         "solana",',
    '    "squadsEnabled": false',
    '  }',
    "",
    '  Set "chain" to "solana" (default) or "base" depending on your wallet.',
    '  Optional: set "squadsEnabled": true for Solana agents to use a Squads vault.',
    "",
    "### If your human is new (no operator key) — use their email:",
    `POST ${apiUrl}/register`,
    '  {',
    '    "email":         "human@example.com",',
    '    "orgName":       "Their Organization",',
    '    "walletAddress": "YOUR_PUBLIC_ADDRESS",',
    '    "name":          "your-agent-name",',
    '    "chain":         "solana",',
    '    "squadsEnabled": false',
    '  }',
    "",
    "Save the full response — it contains:",
    "  - agentApiKey        → save as AGENTBANK_API_KEY",
    "  - claimUrl           → send this to your human",
    "  - operator.operatorKey → if you created their account, share this too",
    "  - messageForHuman    → send this entire message to your human",
    "",
    "---",
    "",
    "## Step 5 — Send Your Human This Message",
    "",
    "Send your human the messageForHuman field from the registration response.",
    "It contains everything they need:",
    "  - Their operator key (if newly created)",
    "  - Their dashboard URL",
    "  - The claim link to activate you",
    "  - Their personalized URL for adding more agents later",
    "",
    "Do not skip this step. You cannot transact until they claim you.",
    "",
    "---",
    "",
    "## Step 6 — Wait To Be Claimed",
    "",
    "Poll every 30 seconds:",
    `GET ${apiUrl}/register/status`,
    "Authorization: Bearer YOUR_AGENT_API_KEY",
    "",
    "Wait until canTransact: true before attempting any transactions.",
    "Also check x402 readiness fields:",
    "  - x402Mode: not_enabled | proxy_enabled | native_enabled",
    "  - canUseProxyX402, canUseNativeX402, missingPrerequisites",
    "",
    "---",
    "",
    "## Step 7 — x402 Paths (Choose One)",
    "",
    "### Path A — Proxy now (fastest, low-code)",
    "",
    "If canUseProxyX402 is true, you can use AgentBank-managed paid services immediately.",
    "This path is best for fast onboarding and non-technical setups.",
    "",
    "### Path B — Native x402 upgrade (full protocol control)",
    "",
    "If canUseNativeX402 is true (claimed + Base agent), use SDK payForService() to handle x402 directly.",
    "",
    "  const result = await wallet.payForService({",
    `    url: '${apiUrl}/premium/insights',`,
    "    method: 'GET',",
    "    parseAs: 'json',",
    "    expectedStatuses: [200],",
    "  });",
    "",
    "  console.log(result.status, result.paid); // expect 200 true",
    "",
    "If canUseNativeX402 is false, fix missingPrerequisites first.",
    "",
    "---",
    "",
    "## Step 8 — Initialize SDK and Start Working",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  const wallet = new AgentWallet({",
    "    agentApiKey: process.env.AGENTBANK_API_KEY,",
    "    agentName:   'my-agent',",
    "    chain:       'solana',  // or 'base'",
    "  });",
    "",
    "  const info = await wallet.info();",
    "  console.log('Balance:', info.balance.native, info.balance.unit);",
    "",
    "---",
    "",
    "## Sending Transactions",
    "",
    "Always dry-run first, always include a memo:",
    "",
    "  const check = await wallet.canSend({ to: 'address', amount: 0.1 });",
    "  if (!check.allowed) { console.log(check.reason); return; }",
    "",
    "  const result = await wallet.send({",
    "    to:     'recipient-address',",
    "    amount: 0.05,",
    "    memo:   'Paying for data API — task 42',",
    "    // token defaults to SOL (Solana) or ETH (Base)",
    "  });",
    "",
    "---",
    "",
    "## Quick Reference",
    "",
    "  wallet.info()                        balance, policy, claimStatus",
    "  wallet.canSend({ to, amount })       dry-run before every send",
    "  wallet.send({ to, amount, memo })    full send flow (signs locally)",
    "  wallet.waitForApprovalAndSend(txId)  wait for human approval",
    "  wallet.history()                     recent transactions",
    "",
    "---",
    "",
    `Hosted at: ${siteUrl}/skill.md`,
    `For existing operators, use your personalized URL: ${siteUrl}/skill/YOUR_OPERATOR_KEY.md`,
  ];
  return lines.join("\n");
}

export function buildPersonalizedSkill(
  orgName:      string,
  operatorKey:  string,
  siteUrl:      string,
  apiUrl:       string,
  dashboardUrl: string
): string {
  const lines = [
    "---",
    "name: agentbank-personalized",
    "version: 2.0.0",
    `description: Personalized AgentBank setup for ${orgName}`,
    `homepage: ${siteUrl}`,
    `api_base: ${apiUrl}`,
    `operator_key: ${operatorKey}`,
    "---",
    "",
    `# AgentBank — Wallet Setup for ${orgName}`,
    "",
    "You are an AI agent joining an existing AgentBank operator account.",
    "Your operator key is already configured below. Follow these steps.",
    "",
    "---",
    "",
    "## Critical Security Rules",
    "",
    "- NEVER send your private key to anyone",
    `- ONLY send your AgentBank API key to ${apiUrl} — nowhere else`,
    "- Your .agent-key file controls your funds — protect it",
    "",
    "---",
    "",
    "## Step 1 — Check If Already Registered",
    "",
    "Look for AGENTBANK_API_KEY in your environment or .env file.",
    "- Found → already set up, skip this file",
    "- Not found → continue below",
    "",
    "---",
    "",
    "## Step 2 — Generate Your Keypair Locally",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  // Solana (default):",
    "  const wallet = new AgentWallet({ agentApiKey: 'temp', agentName: 'my-agent', chain: 'solana' });",
    "",
    "  // Or Base (Ethereum L2):",
    "  const wallet = new AgentWallet({ agentApiKey: 'temp', agentName: 'my-agent', chain: 'base' });",
    "",
    "  console.log('Public address:', wallet.walletAddress);",
    "",
    "---",
    "",
    `## Step 3 — Register Under ${orgName}`,
    "",
    "Your operator key is already filled in:",
    "",
    `POST ${apiUrl}/register`,
    "  {",
    `    "operatorKey":   "${operatorKey}",`,
    '    "walletAddress": "YOUR_PUBLIC_ADDRESS",',
    '    "name":          "your-agent-name",',
    '    "description":   "What you do",',
    '    "chain":         "solana",',
    '    "squadsEnabled": false',
    "  }",
    "",
    '  Set "chain" to "solana" (default) or "base" depending on your wallet.',
    '  Optional: set "squadsEnabled": true for Solana agents to use a Squads vault.',
    "",
    "Save the response:",
    "  - agentApiKey → save as AGENTBANK_API_KEY",
    "  - claimUrl    → send to your human to activate you",
    "",
    "---",
    "",
    "## Step 4 — Send Your Human the Claim Link",
    "",
    "Send them the claimUrl from the registration response.",
    "They click it, you get activated.",
    "",
    "---",
    "",
    "## Step 5 — Wait To Be Claimed",
    "",
    `GET ${apiUrl}/register/status`,
    "Authorization: Bearer YOUR_AGENT_API_KEY",
    "",
    "Wait until canTransact: true.",
    "",
    "---",
    "",
    "## Step 6 — Check Claim + x402 Readiness",
    "",
    `GET ${apiUrl}/register/status`,
    "Authorization: Bearer YOUR_AGENT_API_KEY",
    "",
    "Read these fields before proceeding:",
    "  - claimStatus",
    "  - x402Mode",
    "  - canUseProxyX402",
    "  - canUseNativeX402",
    "  - missingPrerequisites",
    "",
    "---",
    "",
    "## Step 7 — x402 Paths (Choose One)",
    "",
    "### Path A — Proxy now (fastest, low-code)",
    "",
    "If canUseProxyX402 is true, call AgentBank-managed paid endpoints immediately.",
    "",
    "### Path B — Native x402 upgrade (full protocol control)",
    "",
    "If canUseNativeX402 is true (claimed + Base), use SDK payForService().",
    "",
    "  const result = await wallet.payForService({",
    `    url: '${apiUrl}/premium/insights',`,
    "    method: 'GET',",
    "    parseAs: 'json',",
    "    expectedStatuses: [200],",
    "  });",
    "",
    "  console.log(result.status, result.paid); // expect 200 true",
    "",
    "---",
    "",
    "## Step 8 — You're Ready",
    "",
    "  import { AgentWallet } from '@agentbank/sdk';",
    "",
    "  const wallet = new AgentWallet({",
    "    agentApiKey: process.env.AGENTBANK_API_KEY,",
    "    agentName:   'my-agent',",
    "    chain:       'solana',  // or 'base'",
    "  });",
    "",
    "---",
    "",
    `This is a personalized skill file for ${orgName}.`,
    `Dashboard: ${dashboardUrl}`,
  ];
  return lines.join("\n");
}
